project:
  type: website
  output-dir: docs

website:
  title: "MEMELAND"

  page-footer:
    left: "&copy; Copyright 2025, MEMELAND"
    right: "This page is built by Ondřej Mottl with ❤️ and [Quarto](https://quarto.org/)."

  site-url: https://memeland-erc.github.io
  repo-url: https://github.com/MEMELAND-ERC/MEMELAND-ERC.github.io
  issue-url: https://github.com/MEMELAND-ERC/MEMELAND-ERC.github.io/issues
  repo-actions: source

  image: Materials/Logos/MEMELAND.png
  favicon: Materials/Logos/MEMELAND.png

  page-navigation: true
  back-to-top-navigation: true

  navbar:
    title: MEMELAND
    search: true
    tools:
      - icon: github
        href: https://github.com/MEMELAND-ERC/MEMELAND-ERC.github.io
    left:
      - text: About
        href: about.qmd

      - text: Research Teams
        menu:
          - text: The Arctic University of Norway
            href: Team/uit.qmd
          - text: University of Oxford
            href: Team/oxford.qmd
          - text: Swiss Federal Institute of Aquatic Science and Technology
            href: Team/eawag.qmd
          - text: University of Salzburg
            href: Team/salzburg.qmd
          - text: Charles University
            href: Team/cuni.qmd

      - text: People
        href: Team/people.qmd
      
      - text: Current activities
        href: Activities/activities.qmd
      
      - text: Outputs
        href: Outputs/outputs.qmd

format:
  html:
    theme:
      - custom_style.scss
    toc: false
