project:
  type: website
  output-dir: docs/en

profile:
  default: english
  group: [english, german, french, czech, norwegian]

website:
  title: "MEMELAND"

  page-footer:
    left: "&copy; Copyright 2025, MEMELAND"
    right: "This page is built by Ondřej Mottl with ❤️ and [Quarto](https://quarto.org/)."

  site-url: https://memeland-erc.github.io
  repo-url: https://github.com/MEMELAND-ERC/MEMELAND-ERC.github.io
  issue-url: https://github.com/MEMELAND-ERC/MEMELAND-ERC.github.io/issues
  repo-actions: source

  image: Materials/Logos/MEMELAND.png
  favicon: Materials/Logos/MEMELAND.png

  page-navigation: true
  back-to-top-navigation: true

  navbar:
    title: MEMELAND
    search: true
    tools:
      - icon: github
        href: https://github.com/MEMELAND-ERC/MEMELAND-ERC.github.io
      - text: "🌐"
        menu:
          - text: English
            href: ../en
          - text: Deutsch
            href: ../de
          - text: Français
            href: ../fr
          - text: Čeština
            href: ../cs
          - text: Norsk
            href: ../no

format:
  html:
    theme:
      - custom_style.scss
    toc: false
