## Univerzita Karlova

[Laboratoř kvantitativní ekologie](https://ondrejmottl.github.io/lab/about_the_lab.html) na Univerzitě Karlově v Praze, vedená [Dr. Ondřejem Mottlem](/Team/people.qmd#dr.-ondřej-mottl) (odborným asistentem pro ekologii rostlin a Open Science Champion na Univerzitě Karlově), se zaměřuje na zkoumání trendů biodiverzity vegetace v prostorových i časových měřítkách. Laboratoř se specializuje na pokročilé kvantitativní a statistické metody spolu s moderními přístupy datové vědy a strojového učení. Jejich výzkum integruje koncepty a metodiky z různých oborů, včetně makroekologie, paleoekologie, vědy o biodiverzitě a kvantitativní ekologie.

Klíčovým pilířem práce laboratoře je silný závazek k otevřené vědě a vědecké reprodukovatelnosti. Všechny výstupy výzkumu, včetně dat, kódu a metodik, jsou veřejně dostupné a plně reprodukovatelné, což zajišťuje transparentnost a umožňuje široké vědecké komunitě na jejich práci dále stavět. Tento důsledný přístup k principům open science zaručuje, že komplexní prostorové modely a analytické workflow projektu MEMELAND mohou být ověřovány, znovu využívány a dále rozvíjeny výzkumníky po celém světě.

V projektu MEMELAND hraje laboratoř klíčovou roli při integraci multiproxy datasetů generovaných ostatními týmy (sedaDNA, lipidové biomarkery, archeobotanická data a chronologická data) do komplexních prostorových modelů. Pomocí pokročilých kvantitativních paleoekologických metod objasní vzorce biodiverzity a změn využívání krajiny v severní a střední Evropě za poslední dvě tisíciletí. Tato práce pokryje různá prostorová měřítka - od lokálních biomů až po kontinenty - a umožní komplexní porozumění tomu, jak lidské činnosti formovaly dynamiku evropské vegetace v průběhu dějin.

### Lidé

 - [Dr. Ondřej Mottl](/Team/people.qmd#dr.-ondřej-mottl)
