## Université Charles de Prague

Le [Laboratoire d'écologie quantitative](https://ondrejmottl.github.io/lab/about_the_lab.html) à l'Université Charles de Prague, dirigé par [le Dr. Ondřej Mottl](/Team/people.qmd#dr.-ondřej-mottl) (Maître de conférences en écologie végétale et champion de la science ouverte), se concentre sur l'examen des tendances de la biodiversité végétale à différentes échelles spatiales et temporelles. Le laboratoire est spécialisé dans des méthodes quantitatives et statistiques de pointe, ainsi que dans les approches de science des données et d'apprentissage automatique. Leurs recherches intègrent des concepts et des méthodologies issus de la macroécologie, de la paléoécologie, des sciences de la biodiversité et de l'écologie quantitative.

Un pilier central de l'activité du laboratoire est un fort engagement en faveur de la science ouverte et de la reproductibilité scientifique. Tous les résultats de recherche - données, code et méthodologies - sont rendus publiquement accessibles et entièrement reproductibles, garantissant la transparence et permettant à l'ensemble de la communauté scientifique de s'appuyer sur ces travaux. Cet attachement aux principes de la science ouverte garantit que les modèles spatiaux complexes et les flux d'analyse de MEMELAND pourront être vérifiés, réutilisés et prolongés par des chercheurs du monde entier.

Dans MEMELAND, le laboratoire joue un rôle crucial dans l'intégration des ensembles de données multi-proxys générés par les autres équipes (sedaDNA, biomarqueurs lipidiques, données archéobotaniques et données chronologiques) dans des modèles spatiaux complets. Grâce à des méthodes quantitatives avancées en paléoécologie, il mettra en lumière les dynamiques de la biodiversité et des changements d'usage des terres en Europe du Nord et du Centre au cours des deux derniers millénaires. Ce travail couvrira des échelles spatiales variées - des biomes locaux jusqu'aux continents - et permettra une compréhension globale de la manière dont les activités humaines ont façonné la dynamique de la végétation européenne au fil de l'histoire.

### Personnes

 - [Dr. Ondřej Mottl](/Team/people.qmd#dr.-ondřej-mottl)
