## Det sveitsiske føderale instituttet for akvatisk vitenskap og teknologi (Eawag)

Ved Eawag bruker [Prof. Nathalie Dubois](/Team/people.qmd#prof.-dr.-nathalie-dubois) og [Dr. Tobias Schneider](/Team/people.qmd#dr.-tobias-schneider) innsjøsedimenter som naturlige arkiver for å undersøke sammenhengen mellom klima, miljø og mennesker gjennom hele holocen. Innenfor MEMELAND-prosjektet fokuserer arbeidet deres på fekale biomarkører, biomolekyler som steroler og gallesyrer produsert av dyr, for å rekonstruere beitebruk og gjødsling under den «middelalderske jordbruksrevolusjonen».
Forskningen deres dreier seg om spørsmål som: (1) Kan fekale biomarkører gi ny innsikt i tidligere endringer i arealbruk? (2) Kan disse molekylære sporene avdekke romlige og tidslige forskjeller i jordbrukspraksis i Europa? (3) Kan eutrofiering i innsjøer og oksygensvinn knyttes til økt næringstilførsel gjennom fekale biomarkører?

For å undersøke disse spørsmålene og identifisere menneskeskapte spor av arealbruk, integrerer de biomarkørdata med hyperspektral avbildning og kombinerer dette med komplementære geokjemiske og geokronologiske data innhentet av Salzburg-gruppen.

Utover å rekonstruere arealbruk vil dataene fra de fekale biomarkørene (a) bidra til å validere sedaDNA-registreringer av dyr og (b) gi uavhengig dokumentasjon for beiting, gjødsling og til og med direkte menneskelige fekale tilførsler. Biomarkøranalysene vil bli supplert med forbindelsesspesifikk radiokarbondatering av foraldrende bladvoks og analyser av ildfast organisk karbon (ROC) for å tolke pløying og jorderosjon knyttet til husdyrhold. Til slutt skal artsspesifikke plantebiomarkører som miliacin (hirse) og cannabinol (*Cannabis spp.*) brukes til å påvise dyrking av nyttevekster (til mat, medisin og fiber) og praksiser som røyting av hamp.

Resultatene fra Eawag-gruppen vil bidra direkte til MEMELANDs tverrfaglige rammeverk, som bringer sammen arkeobotanikk, sedimentært DNA og sosio-miljømessig modellering for å rekonstruere Europas middelalderlandskap.

### Personer

 - [Prof. Dr. Nathalie Dubois](/Team/people.qmd#prof.-dr.-nathalie-dubois)
 - [Dr. Tobias Schneider](/Team/people.qmd#dr.-tobias-schneider)
