## Švýcarský federální institut pro vědu a technologie vodních zdrojů (Eawag)

V Eawag [Prof. Nathalie Dubois](/Team/people.qmd#prof.-dr.-nathalie-dubois) a [Dr. Tobias Schneider](/Team/people.qmd#dr.-tobias-schneider) využívají jezerní sedimenty jako přírodní archivy pro studium vazeb mezi klimatem, prostředím a člověkem v průběhu holocénu. V rámci projektu MEMELAND se jejich práce soustřeďuje na fekální biomarkery, tedy biomolekuly, jako jsou steroly a žlučové kyseliny produkované živočichy, které slouží k rekonstrukci pastvy a hnojení během „středověké zemědělské revoluce“.
Jejich výzkum se opírá o otázky jako: (1) mohou fekální biomarkery přinést nové poznatky o změnách využívání krajiny v minulosti? (2) Mohou tyto molekulární stopy odhalit prostorové a časové rozdíly v zemědělských praktikách napříč Evropou? (3) Lze eutrofizaci jezer a úbytek kyslíku propojit se zvýšeným přísunem živin doloženým fekálními biomarkery?

Aby tyto otázky zodpověděli a identifikovali antropogenní signatury využívání krajiny, propojují biomarkerová data s hyperspektrálním snímkováním a kombinují je s doplňkovými geochemickými a geochronologickými daty získanými týmem Univerzity v Salcburku.

Kromě rekonstrukce využívání krajiny pomohou data fekálních biomarkerů (a) validovat záznamy živočišné sedaDNA a (b) poskytnout nezávislé důkazy o pastvě, hnojení a dokonce i přímých lidských fekálních vstupech. Biomarkerové analýzy budou doplněny sloučeninově specifickým radiouhlíkovým datováním přestárlých vosků z listů a analýzami refrakterního organického uhlíku (ROC) pro odhad eroze půdy spojené s orbou a chovem hospodářských zvířat. Nakonec budou druhově specifické rostlinné biomarkery, jako miliacin (proso) a cannabinol (*Cannabis spp.*), využity k detekci pěstování plodin (potravina, léčivo, vlákno) a praktik, jako je rosení konopí.

Výsledky týmu Eawag přímo přispějí k interdisciplinárnímu rámci MEMELAND, který propojuje archeobotaniku, sedimentární DNA a socio-environmentální modelování za účelem rekonstrukce středověkých evropských krajin.

### Lidé

 - [Prof. Dr. Nathalie Dubois](/Team/people.qmd#prof.-dr.-nathalie-dubois)
 - [Dr. Tobias Schneider](/Team/people.qmd#dr.-tobias-schneider)
