## Université d'Oxford

L'équipe d'Oxford examinera la manière dont les données de sedaDNA s'articulent avec les données archéobotaniques et polliniques, l'archéologie des établissements et les sources écrites. Nous nous concentrerons sur les changements écologiques (ou les continuités) pendant des périodes charnières, telles que la transition entre la fin de l'époque romaine et la période post-romaine (IVe-VIe siècles), la "révolution agricole" médiévale (Xe-XIIIe siècles) et les crises démographiques du XIVe siècle. L'écologie fonctionnelle des adventices nous permettra de retracer les changements de fertilité et de perturbation des sols, en particulier dans les régions où les systèmes agraires sont devenus de plus en plus étendus et peu intensifs en intrants. L'analyse archéobotanique sera également utilisée pour suivre les changements dans la diversité des cultures et l'apparition de nouvelles plantes cultivées, tandis que les données polliniques nous permettront d'évaluer l'importance relative des terres arables, des pâturages et des forêts. L'impact de la charrue à versoir est d'une importance capitale pour cette période. Elle a entraîné une augmentation des perturbations du sol, reflétée dans l'écologie des adventices des champs. Des expériences de culture menées au laboratoire Lauresham d'archéologie expérimentale exploreront l'impact de la charrue à versoir sur les isotopes stables des cultures et sur l'écologie des adventices, ce qui permettra d'interpréter plus précisément les données isotopiques et botaniques issues des fouilles archéologiques. Les assemblages osseux animaux provenant de sites fouillés seront comparés au sedaDNA et aux biomarqueurs fécaux afin de retracer l'évolution des pratiques d'élevage, par exemple la densité de cheptel ou les variations des proportions entre moutons, bovins et porcs. En travaillant avec des historiens locaux, nous utiliserons les sources écrites aux côtés des archives archéologiques locales pour contextualiser les résultats scientifiques et suivre les changements des régimes agricoles, de la biodiversité et de l'utilisation des terres à l'échelle des sites et des régions.

Nous rassemblerons des données bioarchéologiques provenant des bassins versants des sites en nous appuyant sur des bases de données existantes, y compris des mesures de valeurs isotopiques stables sur les céréales, celles-ci pouvant refléter le statut nutritif et les pratiques de fumure. L'écologie fonctionnelle des adventices sera appliquée aux données archéobotaniques, polliniques et de sedaDNA, ainsi qu'à une nouvelle approche d'écologie fonctionnelle du pâturage. Les données polliniques seront obtenues à partir d'études locales ou de la base de données polliniques européenne ; lorsque cela sera nécessaire, de nouvelles carottes seront prélevées. Une attention particulière sera accordée aux spores coprophiles, qui peuvent fournir des données indépendantes à comparer au sedaDNA et aux biomarqueurs fécaux. Le microcharbon sera également comptabilisé, car l'usage du feu constitue une composante variable de la gestion médiévale des terres. Afin d'établir un ensemble homogène de relevés polliniques fossiles pour l'ensemble de l'Europe, destiné à des comparaisons cartographiques avec nos résultats de sedaDNA, nous utiliserons le workflow FOSSILPOL. Cette méthodologie nous permet de récupérer des données depuis la base Neotoma Paleoecology Database, qui constitue le plus vaste dépôt curé de recherche paléoenvironnementale, et d'appliquer des critères spécifiques au projet afin de sélectionner des données de haute qualité. Les données multi-proxys issues des carottes seront utilisées pour la modélisation spatiale de la végétation, combinée à des analyses fonctionnelles en écologie afin d'évaluer les régimes de gestion des terres.

### Personnes

 - [Prof. Helena Hamerow](/Team/people.qmd#prof.-helena-hamerow)
 - [Prof. Amy Bogaard](/Team/people.qmd#prof.-amy-bogaard)
 - [Dr. Michael Charles](/Team/people.qmd#dr.-michael-charles)
 - [Elizabeth Stroud](/Team/people.qmd#elizabeth-stroud)
