## Oxfordská univerzita

Oxfordský tým bude zkoumat, jak se data sedaDNA shodují s archeobotanickými a pylovými daty, archeologií sídlišť i písemnými prameny. Zaměříme se na ekologické změny (nebo kontinuitu) v klíčových obdobích, jako je přechod od pozdně římského k porímskému období (4.-6. století), středověká „zemědělská revoluce“ (10.-13. století) a demografické krize 14. století. Funkční ekologie plevelů nám umožní sledovat změny úrodnosti půdy a míry narušení, zejména v regionech, kde se orné hospodaření stalo rozsáhlejším a méně vstupně náročným. Archeobotanická analýza se využije také ke sledování změn diverzity plodin a objevování nových plodin, zatímco pylová data pomohou určit relativní význam orné půdy, pastvin a lesa. V tomto období je kriticky důležitý dopad těžkého radličného pluhu. Vedl k nárůstu narušení půdy, což se odráží v ekologii plevelů na orné půdě. Kultivační experimenty v Laboratoři experimentální archeologie Lauresham prověří vliv tohoto pluhu na stabilní izotopy plodin a ekologii plevelů, aby bylo možné přesněji interpretovat izotopová i plevelná data z archeologických výzkumů. Soubory zvířecích kostí z vykopaných sídlišť budou porovnány se sedaDNA a fekálními biomarkery pro sledování změn v chovatelských praktikách, např. hustoty stád nebo poměru ovcí, skotu a prasat. Ve spolupráci s regionálními historiky využijeme písemné prameny spolu s lokálními archeologickými záznamy k zasazení vědeckých výsledků do kontextu a ke sledování změn zemědělských režimů, biodiverzity a využívání krajiny na úrovni jednotlivých lokalit i regionů.

Shromáždíme bioarcheologická data z povodí jednotlivých lokalit s využitím existujících databází, včetně měření hodnot stabilních izotopů obilnin, které mohou odrážet živinový stav a hnojení. Funkční ekologie plevelů bude aplikována na archeobotanická, pylová a sedaDNA data spolu s novým přístupem k funkční ekologii spásání. Pylová data budou čerpána z lokálních studií nebo z European Pollen Database; tam, kde to bude nutné, budou odebrána nová jádra. Zvláštní pozornost bude věnována koprofilním sporám, které mohou poskytnout nezávislá data pro srovnání se sedaDNA a fekálními biomarkery. Počítán bude i mikrouhlík, protože využívání ohně je proměnlivou součástí středověkého hospodaření v krajině. Pro vytvoření jednotného souboru fosilních pylových záznamů napříč Evropou pro mapové srovnání s našimi výsledky sedaDNA použijeme workflow FOSSILPOL. Tato metodika nám umožní získat data z databáze Neotoma Paleoecology Database, která je nejrozsáhlejším kurátorovaným repozitářem paleoekologického výzkumu, a aplikovat projektová kritéria pro kuraci vysoce kvalitních dat. Multiproxy data z jader budou použita pro prostorové modelování vegetace v kombinaci s funkční ekologickou analýzou za účelem posouzení režimů hospodaření v krajině.

### Lidé

 - [Prof. Helena Hamerow](/Team/people.qmd#prof.-helena-hamerow)
 - [Prof. Amy Bogaard](/Team/people.qmd#prof.-amy-bogaard)
 - [Dr. Michael Charles](/Team/people.qmd#dr.-michael-charles)
 - [Elizabeth Stroud](/Team/people.qmd#elizabeth-stroud)
