## Arkticka univerzita Norska

Vyzkumne centrum ArcEcoGEN pri Tromso Museum, Arkticke univerzite Norska (UiT), je hostitelskou instituci projektu MEMELAND. V Tromso [Prof Tony Brown](/Team/people.qmd#prof.-tony-g-brown) a jeho tym projekt koordinuji a specializuji se na extrakci a analyzu starobyle DNA ze sedimentu (sedaDNA). Ve spolupraci se strasburskym tymem provozuje Tromso terenni odberovy tym, ktery bude vrtat jezerni i nektere mokradni lokality v severnich a zapadnich castech studovane oblasti vcetne cele Skandinavie, stredni Evropy, severniho Nemecka a Francie. Projekt navic vyuziva material z mnoha dalsich instituci vhodny pro analyzu sedaDNA. Celkove bude zpracovano vice nez 100 jader a 4000-8000 vzorku, ktere pomohou popsat promeny evropske biodiverzity za poslednich 2000 let, tedy od rimskeho obdobi. To bude umozneno vysoce presnym datovanim (viz sekce Salzburg) a doplneno fekalnimi i dalsimi biomarkery (tym Eawag) a archeobotanickymi studiemi (tym Oxford).

Skupina v Tromso jsou specialisti na extrakci a analyzu sedaDNA z ruznych paleoekologickych kontextu, predevsim z jezer, ale i z mokradu, niv, svahovych sedimentu a archeologickych lokalit. Tato studie se zameruje na mala jezera v zemedelske krajine severozapadni Evropy. Hlavne pouzivame dve metodiky: zaprvne amplikonovou neboli metabarcoding analyzu, pri niz je DNA ve vzorku cilene vybrana a amplifikovana pred sekvenovanim. Jde o hlavni metodiku projektu, protoze se ukazala jako nejspolehlivejsi a nejefektivnejsi vzhledem k nakladum. Obvykle je vsak omezena na urcite skupiny organismu vcetne cevnatych rostlin a obratlovcu, i kdyz lze amplifikovat i jinou DNA. Soucasne ji nelze vnitrne autentifikovat podle poskozeni DNA a obtizneji se dostava pod druhovou uroven. Tato omezeni je mozne prekonat neamplikonovym neboli shotgun sekvenovanim. Tromso tym neustale vyviji nove metody, aby zlepsil hloubku informaci ziskanych z techto sedimentarnich prostredi a lepe porozumel omezenim i zkresleni dat.

V mnoha pripadech budou tato data kombinovana s biomarkery a archeobotanickymi daty vcetne pylu, aby vznikla komplexnejsi rekonstrukce minulych zemedelskych ekosystemu. To zahrnuje nejen plodiny a domestikovana zvireta, ale take plevele, synantropni druhy (parazite, skudci, komenzalove apod.) a promeny nizinnnych ekosystemu severozapadni Evropy. Data umozni vytvorit novy pribeh evropske biodiverzity na dvou urovnich: pribehy jednotlivych lokalit a druhu i regionalni biome-vzorove struktury definujici biodiverzitu severozapadni Evropy. Jde o dulezite dukazy pro snahu udrzet vysokou biodiverzitu a kvalitu zivotniho prostredi tvarem v tvar klimaticke zmene i rostoucimu tlaku populace a technologickeho rozvoje. Zajimave je, ze podobna situace zde uz byla; dejiny zemedelstvi od rimske pritomnosti v severni Evrope jsou historii trvaleho rustu populace a prosperity, avsak se slozitymi dopady na biodiverzitu a prirodu. Tuto archeologickou a historickou dimenzi rozviji tym Oxford. Vysledky budou publikovany na ruznych prostorovych urovnich a budou slouzit k pochopeni promene krajiny a ekologie v cele oblasti, vcetne prostoroveho modelovani realizovaneho ve spolupraci s Laboratori kvantitativni ekologie na Univerzite Karlove v Praze.

### Lide

 - [Prof. Tony G Brown](/Team/people.qmd#prof.-tony-g-brown)
 - [Prof. Inger G Alsos](/Team/people.qmd#prof.-inger-g-alsos)
 - [Dr. Oliver Kern](/Team/people.qmd#dr.-oliver-kern)
 - [Dr. Ying Liu](/Team/people.qmd#dr.-ying-liu)
 - [Katja Hakli](/Team/people.qmd#katja-häkli)
