## Université arctique de Norvège (UiT)

Le Centre de recherche ArcEcoGEN au sein du Musée de Tromsø, à l'Université arctique de Norvège (UiT), est l'institution hôte de MEMELAND. À Tromsø, [le Prof. Tony Brown](/Team/people.qmd#prof.-tony-g-brown) et son équipe administrent le projet et sont spécialisés dans l'extraction et l'analyse de l'ADN ancien provenant de sédiments (sedaDNA). En collaboration avec l'équipe de Strasbourg, Tromsø dirige une équipe de terrain qui effectue des carottages dans des lacs et des zones humides dans les parties nord et ouest de la zone d'étude, incluant toute la Scandinavie, l'Europe centrale, le nord de l'Allemagne et la France. Au total, plus de 100 carottes et 4 000 à 8 000 échantillons seront utilisés pour étudier l'évolution de la biodiversité européenne au cours des 2 000 dernières années. Ces analyses seront complétées par des datations haute résolution (équipe de Salzbourg), des biomarqueurs fécaux et autres (équipe Eawag) ainsi que des études archéobotaniques (équipe d'Oxford).

L'équipe de Tromsø est spécialisée dans l'extraction et l'analyse du sedaDNA dans divers contextes paléoenvironnementaux : principalement des lacs, mais aussi des zones humides, des plaines inondables, des sédiments de versant et des sites archéologiques. Cette étude se concentre sur de petits lacs intégrés dans les paysages agricoles du nord-ouest de l'Europe. Nous utilisons principalement deux méthodologies : d'une part l'analyse par amplicons ou métabarcoding, dans laquelle l'ADN présent dans un échantillon est ciblé et amplifié avant le séquençage. Il s'agit de la méthode de travail centrale du projet, car elle s'est révélée la plus fiable et la plus avantageuse en termes de coût. Toutefois, elle reste en général limitée à certains groupes d'organismes, notamment les plantes vasculaires et les vertébrés, même si d'autres ADN peuvent également être amplifiés. Elle ne peut pas non plus être authentifiée de manière intrinsèque à partir des motifs de dégradation, et elle ne permet pas facilement d'aller au-dessous du niveau de l'espèce. Ces limites peuvent être dépassées grâce au séquençage non basé sur les amplicons, ou shotgun. L'équipe de Tromsø développe continuellement de nouvelles méthodes afin d'améliorer la profondeur des informations extraites de ces environnements sédimentaires et de mieux comprendre les limites et les biais des données.

Dans de nombreux cas, ces données seront combinées avec les données de biomarqueurs et les données archéobotaniques, y compris le pollen, afin de proposer une reconstruction plus holistique des écologies agricoles passées. Cela inclut non seulement les cultures et les animaux domestiques, mais aussi les adventices, les espèces synanthropes (parasites, ravageurs, commensaux, etc.) et les changements affectant les écosystèmes de plaine du nord-ouest de l'Europe. Ces données permettront d'élaborer un nouveau récit de la biodiversité européenne à deux niveaux : l'histoire de sites et d'espèces particuliers, et les modèles régionaux à l'échelle des biomes qui définissent la biodiversité du nord-ouest de l'Europe. Il s'agit d'un ensemble de preuves important pour préserver une biodiversité élevée et une bonne qualité environnementale face à la fois au changement climatique et à la pression croissante liée à l'augmentation de la population et au développement technologique. Fait intéressant, cette situation s'est déjà produite auparavant : l'histoire de l'agriculture depuis la présence romaine dans le nord de l'Europe est celle d'une croissance démographique et d'une prospérité continues, mais aussi de conséquences complexes pour la biodiversité et la nature. Cette dimension archéologique et historique est au cœur du travail de l'équipe d'Oxford. Les résultats seront publiés à différentes échelles spatiales et serviront à comprendre l'évolution des paysages et de l'écologie dans l'ensemble de la région, y compris au moyen de modélisations spatiales menées en collaboration avec le Laboratoire d'écologie quantitative de l'Université Charles de Prague.

### Personnes

 - [Prof. Tony G Brown](/Team/people.qmd#prof.-tony-g-brown)
 - [Prof. Inger G Alsos](/Team/people.qmd#prof.-inger-g-alsos)
 - [Dr. Oliver Kern](/Team/people.qmd#dr.-oliver-kern)
 - [Dr. Ying Liu](/Team/people.qmd#dr.-ying-liu)
 - [Katja Häkli](/Team/people.qmd#katja-häkli)
