---
date: 2026/04/01
date-format: long
date-modified: last-modified
sidebar: true
toc: true
toc-depth: 2
listing:
  - id: team-news
    contents: "../Activities/news/*.qmd"
    include:
      categories: "cuni"
    sort: "date desc"
    type: grid
    grid-item-border: true
    max-description-length: 300
    fields: [title, description, date]
    page-size: 3
---

## Charles University

The [Laboratory of Quantitative Ecology](https://ondrejmottl.github.io/lab/about_the_lab.html) at Charles University in Prague, led by [Dr. Ondřej Mottl](/Team/people.qmd#dr.-ondřej-mottl) (Assistant Professor for Plant Ecology and Open Science Champion at Charles University), focuses on examining vegetation biodiversity trends across spatial and temporal scales. The laboratory specializes in cutting-edge quantitative and statistical methods, alongside state-of-the-art data science and machine learning approaches. Their research integrates concepts and methodologies from various fields, including macroecology, palaeoecology, biodiversity science, and quantitative ecology.

A core pillar of the laboratory's work is a strong commitment to open science and scientific reproducibility. All research outputs, including data, code, and methodologies, are made publicly available and fully reproducible, ensuring transparency and enabling the broader scientific community to build upon their work. This dedication to open science principles ensures that MEMELAND's complex spatial models and analytical workflows can be verified, reused, and extended by researchers worldwide.

In MEMELAND, the laboratory plays a crucial role in integrating the multi-proxy datasets generated by the other teams (sedaDNA, lipid biomarkers, archaeobotanical data, and chronological data) into comprehensive spatial models. Using advanced quantitative palaeoecological methods, they will elucidate patterns of biodiversity and land-use change across northern and central Europe over the last two millennia. This work will span diverse spatial scales—from local biomes to continents—enabling a holistic understanding of how human activities have shaped European vegetation dynamics throughout history. The laboratory's expertise in developing new methodologies ensures that MEMELAND remains at the forefront of ecological science, expanding our understanding of long-term vegetation patterns and their drivers.

### People

 - [Dr. Ondřej Mottl](/Team/people.qmd#dr.-ondřej-mottl)

### News

::: {#team-news}
:::