blank_issues_enabled: false
contact_links:
  - name: Contact the MEMELAND team
    url: https://memeland-erc.github.io/en/About/about.html
    about: For general questions about the project, please visit the About page or contact the team directly.
